#ifndef __JSON_CONFIG_H__
#define __JSON_CONFIG_H__

#define DRIVER_JSON_ENABLED 1

#define DRIVER_CAN_JSON_ENABLED 0
#define DRIVER_ADC_JSON_ENABLED 0
#define DRIVER_I2C_JSON_ENABLED 0
#define DRIVER_SPI_JSON_ENABLED 0
#define DRIVER_UART_JSON_ENABLED 0

#endif // __JSON_CONFIG_H__